one_compliance/one_compliance/doctype/compliance_sub_category/compliance_sub_category.json
-> Edited the doctype Compliance Sub Category
-> Added option for repetition
No
- Chrome : yes
=> feat: Edited the doctype Compliance Sub Category

one_compliance/fixtures/document_register_type.json, one_compliance/hooks.py, one_compliance/one_compliance/doctype/document_register_type/document_register_type.json, one_compliance/one_compliance/doctype/general_register_type/general_register_type.json, one_compliance/one_compliance/doctype/outward_register/outward_register.js, one_compliance/one_compliance/doctype/outward_register/outward_register.json, one_compliance/one_compliance/doctype/outward_register/outward_register.py, one_compliance/one_compliance/doctype/outward_register/test_outward_register.py
Created outward register doctype and edited inward register doctype
Naming series applied for register and document type doctype
No
- Chrome
=> feat: Created outward register doctype and edited inward register doctype

one_compliance/hooks.py, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.js, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.json, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py, one_compliance/one_compliance/doctype/compliance_agreement/test_compliance_agreement.py, one_compliance/one_compliance/doctype/compliance_category_details/compliance_category_details.js, one_compliance/one_compliance/doctype/compliance_category_details/compliance_category_details.json, one_compliance/one_compliance/doctype/compliance_category_details/compliance_category_details.py, one_compliance/one_compliance/doctype/compliance_category_details/test_compliance_category_details.py, one_compliance/one_compliance/doctype/compliance_category_list/compliance_category_list.json, one_compliance/one_compliance/doctype/compliance_category_list/compliance_category_list.py
-> Create a doctype compliance agreement
No
- Chrome
=> feat: Create a new doctype Compliance Agreement

one_compliance/fixtures/custom_docperm.json
Added outward register doctype permissions to super admin role
- Chrome
=> feat:Added outward register doctype permissions to super admin role

one_compliance/one_compliance/doctype/inward_register/inward_register.json, one_compliance/one_compliance/doctype/outward_register/outward_register.json
->Edited doctype Outward Register and fetched values from Inward Register
No
- Chrome : yes
Outward Register
=> chore: Edited doctype Outward Register and fetched values from Inward Register

one_compliance/one_compliance/workspace/one_compliance/one_compliance.json
Create workspace for one compliance and added shortcuts
No
- Chrome
=> feat: Create workspace for one compliance

one_compliance/fixtures/workflow.json, one_compliance/fixtures/workflow_action_master.json, one_compliance/fixtures/workflow_state.json, one_compliance/hooks.py
Created workflow for Compliance Agreement Doctype
No.
- Chrome
=> feat : Created workflow for Compliance Agreement Doctype

one_compliance/one_compliance/doctype/purpose/purpose.js, one_compliance/one_compliance/doctype/purpose/purpose.json, one_compliance/one_compliance/doctype/purpose/purpose.py, one_compliance/one_compliance/doctype/purpose/test_purpose.py
Create purpose doctype
No
- Chrome
=> feat: Create Purpose doctype

one_compliance/fixtures/custom_docperm.json, one_compliance/fixtures/workflow.json, one_compliance/fixtures/workflow_action_master.json, one_compliance/fixtures/workflow_state.json, one_compliance/hooks.py, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.js, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.json, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py, one_compliance/one_compliance/doctype/compliance_category_details/compliance_category_details.json, one_compliance/one_compliance/doctype/compliance_sub_category/compliance_sub_category.json
-.Added Valid From and Valid Till date in Compliance Agreement Doc type and set Default date of Valid From is Today.
-.Removed Contact Details from Compliance Agreement Doc type.
-.Added Signature Section in Compliance Agreement Contain Customer and authority Signature and make it as Mandatory
field after Request for Review and Sent to Customer
-.Fetch rate from sub category to Compliance Agreement Doc type and find Total
No. 
- Chrome
=> feat : Added new Features in Compliance Agreement Doctype

one_compliance/fixtures/custom_docperm.json, one_compliance/fixtures/role.json, one_compliance/hooks.py, one_compliance/one_compliance/doctype/inward_register/inward_register.js, one_compliance/one_compliance/doctype/inward_register/inward_register.json, one_compliance/one_compliance/doctype/inward_register/inward_register.py
-> Customised inward register
-> Apply filter in inward register
-> Create customer button in inward register to create outward register
-> Create a new role compliance manager
No
- Chrome
=> feat: Customised Inward register doctype

one_compliance/one_compliance/doctype/compliance_category/compliance_category.json
Apply filter in Compliance category
No
- Chrome
=> feat : Apply filter in Compliance category

one_compliance/one_compliance/doctype/notification_template/notification_template.js, one_compliance/one_compliance/doctype/notification_template/notification_template.json, one_compliance/one_compliance/doctype/notification_template/notification_template.py, one_compliance/one_compliance/doctype/notification_template/test_notification_template.py
Created Notification Template Doctype
No
- Chrome
=> feat : Created Notification Template Doctype

one_compliance/fixtures/notification_template.json, one_compliance/hooks.py, one_compliance/one_compliance/utils.py
Added notification template in fixtures
No.
- Chrome
=> feat : Added notification template in fixtures

one_compliance/one_compliance/custom/task.json
-> Issue fixed in Task
No
- Chrome : yes
=> fix: fix issue in Task

one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.js, one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.json, one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.py, one_compliance/one_compliance/doctype/compliance_settings/test_compliance_settings.py
Created Compliance Setting Doc type
No
- Chrome
=> feat: Created Compliance Setting Doctype

one_compliance/hooks.py, one_compliance/one_compliance/utils.py
- Sent Notification to employee when Director assigning new task
- Sent Notification to employee  before the due date
- Sent Notification to employee if any escalation from higher authority
No. 
- Chrome
=> feat: Email Notification For Employee

one_compliance/fixtures/workflow_state.json, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.json, one_compliance/one_compliance/doctype/inward_register/inward_register.json, one_compliance/one_compliance/doctype/outward_register/outward_register.js, one_compliance/one_compliance/doctype/outward_register/outward_register.json
Issues fixed in certain doctype
No
- Chrome
=> fix: Issues fixed

one_compliance/hooks.py, one_compliance/one_compliance/doc_events/customer.py, one_compliance/one_compliance/doc_events/project.py, one_compliance/one_compliance/doc_events/task.py, one_compliance/one_compliance/utils.py, one_compliance/public/js/customer.js, one_compliance/public/js/project.js, one_compliance/public/js/task.js
-> Applied dialog instance to view customer credentials in project and task
No
- Chrome
=> feat: Applied dialog instance to view customer credentials in project and task

one_compliance/hooks.py, one_compliance/one_compliance/doc_events/customer.py, one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.json, one_compliance/public/js/customer.js
Create user from Customer
No
- Chrome - Yes
- Opera Mini
- Safari
=> feat: User Creation from Customer

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
Update issue in migration
- Chrome
=> fix:Update issue in migration

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.json, one_compliance/one_compliance/doctype/compliance_sub_category/compliance_sub_category.json, one_compliance/one_compliance/doctype/digital_signature/digital_signature.json, one_compliance/one_compliance/doctype/staff_assignment/staff_assignment.json
Edited Compliance sub category doc type and fetched values from compliance category
Added fields for department, head of department and Staff assignment
No
- Chrome
=> fix: Edited Compliance sub category doctype and fetched values from compliance category

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.json, one_compliance/one_compliance/doctype/compliance_category/compliance_category.json, one_compliance/one_compliance/doctype/compliance_sub_category/compliance_sub_category.json, one_compliance/one_compliance/doctype/credential_details/credential_details.json, one_compliance/one_compliance/doctype/customer_credentials/customer_credentials.json, one_compliance/one_compliance/doctype/digital_signature/digital_signature.json, one_compliance/one_compliance/doctype/digital_signature/digital_signature.py, one_compliance/one_compliance/doctype/digital_signature_details/digital_signature_details.json, one_compliance/one_compliance/doctype/inward_register/inward_register.js, one_compliance/one_compliance/doctype/inward_register/inward_register.json, one_compliance/one_compliance/doctype/outward_register/outward_register.js, one_compliance/one_compliance/doctype/outward_register/outward_register.json, one_compliance/one_compliance/utils.py
-> Created add/view digital signature custom button inward and outward register
-> Validated duplicate entry of  digital signature
-> Created a dialog box in inward and outward register
-> Renamed a checkbox in compliance agreement 
No.
- Chrome
=> Created add/view digital signature custom button inward and outward register

one_compliance/hooks.py, one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.json, one_compliance/one_compliance/doctype/digital_signature/digital_signature.json, one_compliance/one_compliance/utils.py
Notification on expiration of digital signature before the expiry date
- No
- Chrome : yes
=> feat: Notification on expiration of digital signature

one_compliance/one_compliance/doctype/compliance_category/compliance_category.js, one_compliance/one_compliance/doctype/compliance_category/compliance_category.json, one_compliance/one_compliance/doctype/compliance_executive/compliance_executive.json, one_compliance/one_compliance/doctype/compliance_executive/compliance_executive.py, one_compliance/one_compliance/doctype/compliance_sub_category/compliance_sub_category.js, one_compliance/one_compliance/doctype/compliance_sub_category/compliance_sub_category.json
-> Fetch HOD from department
-> Added a checkbox named Enabled
-> Changed the name of child table to compliance executive and added filters to get active employee
-> Added fields Month and Date
- No
- Chrome :yes
=> feat: Edited doctype Compliance Subcategory

one_compliance/fixtures/workflow.json, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.js, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.json, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py, one_compliance/public/js/department.js
-> Created a button to set status to hold and Open
-> Removed bank details from compliance Agreement
No
- Chrome
=> feat :Edited Compliance Agreement doctype

one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.js, one_compliance/one_compliance/doctype/inward_register/inward_register.json, one_compliance/one_compliance/doctype/outward_register/outward_register.json, one_compliance/one_compliance/doctype/outward_register/outward_register.py
-> Fixed issues in Inward Register and Outward Register
- No. 
- Chrome : yes
=> fix: Fixed issues

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
Indentation error on agreement
=> fix: Indentation error on agreement

one_compliance/one_compliance/workspace/business_executive/business_executive.json, one_compliance/one_compliance/workspace/director/director.json, one_compliance/one_compliance/workspace/head_of_department/head_of_department.json
Updated workspace with number cards and charts to the roles
- Chrome
=> fix:Updated workspace with number cards and charts to the roles

one_compliance/one_compliance/workspace/business_executive/business_executive.json, one_compliance/one_compliance/workspace/director/director.json, one_compliance/one_compliance/workspace/head_of_department/head_of_department.json
Updated each workspace with new changes
- Chrome
=> fix:Updated workspace with new changes

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.json
Fixed the customer type issue in compliance agreement.
- Chrome
=> fix:Fixed customer type issue in compliance agreement

one_compliance/hooks.py, one_compliance/one_compliance/doc_events/task.py
Appended Users to User table in Project
No
- Chrome
=> feat: Appended Users to User table in Project

one_compliance/one_compliance/doctype/credential_type/credential_type.json, one_compliance/public/js/task.js
Added compliance sub category in credential type and applied filters for view credential dialogue in task
No
- Chrome
=> feat: Added compliance sub category in credential type and applied filters for view credential dialogue in task

one_compliance/one_compliance/workspace/director/director.json, one_compliance/one_compliance/workspace/executive/executive.json, one_compliance/one_compliance/workspace/head_of_department/head_of_department.json, one_compliance/one_compliance/workspace/manager/manager.json, one_compliance/one_compliance/workspace/senior_manager/senior_manager.json
Updated all workspace with assigned project's shortcut
- Chrome
=> feat:Updated workspace with assigned project's shortcuts

one_compliance/fixtures/notification_template.json
Notification content issue
No
- Chrome
=> fix: Notification content issue

one_compliance/fixtures/workflow.json, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.js, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
Compliance Agreement Deletion
No
- Chrome
=> feat: Compliance Agreement Deletion

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
Added year and month for recurring project
No
- Chrome
=> fix: Added year and month for recurring project

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.js, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
Issues in Compliance Category Details child table.
No
- Chrome
=> fix: Issues in Compliance Category Details child table

one_compliance/fixtures/notification_template.json
Issue fixed in Notification Template
No
- Chrome
=> fix: Issue fixed in Notification Template

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
Notification while task assigning
No
- Chrome
=> fix: Notification while task assigning

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
- Chrome
- Opera Mini
- Safari
=> fix: project name variable convert to string

one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.js, one_compliance/one_compliance/doctype/compliance_settings/compliance_settings.py
- Chrome
- Opera Mini
- Safari
=> feat:project manual creation

one_compliance/fixtures/module_profile.json
=> fix: HR Permissions

one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.js, one_compliance/one_compliance/doctype/compliance_agreement/compliance_agreement.py
- Chrome
- Opera Mini
- Safari
=> minor fixes in agreement

one_compliance/one_compliance/doctype/compliance_category/compliance_category.json, one_compliance/one_compliance/doctype/compliance_sub_category/compliance_sub_category.json
- Chrome
- Opera Mini
- Safari
=> fix:minor fixes

one_compliance/fixtures/notification_template.json
Changed email notification template
- Chrome
=> Notification template

one_compliance/one_compliance/doctype/director/director.js, one_compliance/one_compliance/doctype/director/director.json, one_compliance/one_compliance/doctype/director/director.py, one_compliance/one_compliance/doctype/director/test_director.py, one_compliance/one_compliance/workspace/compliance_director/compliance_director.json
- Chrome
- Opera Mini
- Safari
=> fix:rename director workspace and add director doctype

one_compliance/one_compliance/report/employee_checkin_summary/employee_checkin_summary.js, one_compliance/one_compliance/report/employee_checkin_summary/employee_checkin_summary.py
Changed default from date to start date of the month and to date to month end.
- Chrome
=> feat:changed default from date and to date
